/**
 * Node.js adapter — full SDK surface (HTTP/SSE/WS/RAW + XaiopWs listen/connect).
 */

export {
  ALL_STREAM_MODES,
  cloneJson,
  CompatPolicy,
  COMPAT_FIX_DEFAULTS,
  COMPAT_FIX_IDS,
  DotCheckpointEngine,
  DOT_POLICY,
  encode,
  encodePhaseJson,
  encodePhaseObject,
  encodeSync,
  formatInjectResult,
  formatJsonPath,
  HISTORY_NODE_KIND,
  isStreamBusy,
  LINE_KIND,
  LiveXaiopParser,
  materializeSnapshot,
  MERGE_CONFLICT,
  mergeJson,
  mergeToJson,
  mergeToXaiop,
  normalizeModes,
  parseAsync,
  parseJsonPath,
  parseSync,
  ParseHistory,
  PROTOCOL_VERSION,
  SDK_VERSION,
  STREAM_IDLE_LIKE,
  STREAM_MODES,
  STREAM_STATUS,
  TYPE,
  TYPE_SCHEMA_FRAME_PREFIX,
  TypeChecker,
  TypeFreezeSession,
  TypeRegistry,
  XaiopEncodeError,
  XaiopEngine,
  XaiopFragment,
  XaiopSyntaxError,
  XaiopTypeError,
  arrayType,
  canonicalizeType,
  classifyLine,
  classifyValue,
  emptyLineView,
  encodeTypeSchemaFrame,
  objectType,
  parseTypeSurface,
  runLineInterceptChain,
  applyAnnotationSpans,
  encodeAsSiblingLines,
  pathEscapesTypeCheck,
  tryParseTypeSchemaFrame,
  typeCompatible,
  typeToString,
  valueMatchesType,
} from "../core/index.js";

export { openTransport, TRANSPORT_KIND } from "./transport.js";
export { XaiopStream } from "./XaiopStream.js";
export {
  listen,
  XaiopWs,
  XaiopWsConnection,
  XaiopWsHub,
} from "./ws/index.js";
